name: build_and_test

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Download dependencies
        run: go mod download

      - name: Build binary
        run: go build -v -o ./../../cmd/ ./...

      - name: Run go vet
        run: go vet ./...

      - name: Run tests
        run: go test -race -vet=off ./...
